### ISSUE TITLE
Testing Strategy Question

### ISSUE THREAD

**Issue by joshuanapoli** [ospfranco/react-native-quick-sqlite#104]
How do you typically test code that depends on react-native-quick-sqlite?

Right now, we generally don't write tests near react-native-quick-sqlite or else we crudely stub the library.

I'd like to improve our testing in this area, but I'm faced with either re-implementing quick-sqlite for node or maybe doing something with detox.

**Comment by ospfranco** [comment]
Because JSI bindings are dependent on the hermes/JSC jsi code and are also C++, it is not really possible to write tests outside the device/simulator. 

On the example app you can find code on how to do an in-app testing suit via a stub setup with mocha. If you want to run indepedent of device/simulator the approach I would suggest is spy/mock the calls and implement with a node implementation, it shouldn't be too hard anyways.
