### ISSUE TITLE
Large operations are causing UI Freeze

### ISSUE THREAD

**Issue by EduFrazao** [ospfranco/react-native-quick-sqlite#21]
Hi! I'm using quick sqlite version 2.0.1, and sometimes when I need to persist some large datasets here, my UI completely freezes.
Using perf monitor, I can see that UI FPS keeps 60FPS, but JS shows "-2.1".

I ran this commands inside a BEGIN TRANSATION and COMMIT statements, and some transactions inserts 100k records.
This lib is so fast, that this rows takes only 8 seconds to be persisted.

As far as I know, React Native keep a separate thread for JavaScript execution right? Do you have any tips in how to keep this heavy work running concurrently, without having so mutch impact on the UI thread? Do you think that this can be related to JSI behavior?

**Comment by ospfranco** [comment]
You need to explain your problem in more detail, including some code. From what I understand you are using the low-level API and executing raw SQL queries, right?

You might be misunderstanding how the JSI bridge works. JSI calls (at least the ones I implemented) even though quite fast are sync, therefore if you call a javascript/JSI function 100k times (which I assume is what you are doing to insert your rows) then you will have 100k blocking function calls and so on. 

What you need is an async call that does not block your javascript code while SQLite is processing your data, but I gave up on this async method because it's too complicated to set up from C++ code and I don't have more time to put into the library.

If you really need this, you can take a look at some of the other JSI libraries, vision-camera uses reanimated worklets which somehow defer work and do not block the JS thread. I just don't have the time to pour so much work nowadays. So you will have to create a PR on your own.

**Comment by EduFrazao** [comment]
Hi @ospfranco . Thank you for your answer..
Yes, i'm using the low level API, behind a Facade Service. This services holds a reference to a IDBConnection object, that I receive when I use the openDatabase exported function.

So, basically I run a BEGIN TRASACTION statement, iterate over 100k rows that issues updates/inserts and latter I run a COMMIT;

This very large operations are very specific. They are not common, only occour when our users need to feed the application with data that they will need to have avaliable offline.

So, on your point of view, maybe the IBConnection object maybe must have a "batch" method that will took a set of sql commands and parameters, and internally in the C++ code start another thread to do this operation, and callback.

Here some code examples on my application:

`
private runInTransaction(scope: (tx: Transaction) => void, db?: ConnectionWrapper): Promise<Transaction> {
    const connection = db || this.getDatabase();
    return new Promise((resolve, reject) => {
      this.transactionMutex.acquire().then((release) => {
        try {
          connection.executeSql('BEGIN TRANSACTION');
          const transaction = new TransactionImpl(connection);
          scope(transaction);
          connection.executeSql('COMMIT');
          resolve(transaction);
        } catch (e) {
          connection.executeSql('ROLLBACK');
          reject(e);
        } finally {
          release();
        }
      });
    });
  }

executeBatchInSingleTransaction(querys: any[]): Promise<void> {
    return new Promise((resolve, reject) => {
      if (querys.length) {
        this.openTransaction((tx) => {
          querys.forEach((query) => {
            if (Array.isArray(query)) {
              const sql = query[0];
              const params = query.length > 1 ? query[1] : undefined;
              tx.executeSql(sql, params);
            } else if (typeof query === 'string') {
              tx.executeSql(query);
            }
          });
        })
          .then(() => {
            resolve();
          })
          .catch(reject);
      } else {
        resolve();
      }
    });
  }
`

This "connection" object is just a wrapper to the IBConnection object from the low level API. Its running rock solid.

**Comment by ospfranco** [comment]
You got the gist of it correctly, but just to make it clear: JSI calls are **sync**, it doesn't matter if you wrap them in promises, if you have such a large batch of data you won't be able to do it any faster with the current implementation, because it will still freeze the javascript thread while waiting for C++ to process your data.

**What you need in order to get this working smoothly is** is batch processing + async JSI calls, which are possible (one example is re-animated worklets, which are also used by vision-camera). Adding a batch processing method should be somewhat trivial to implement, but it will not really solve your blocking problem only improve it. 

Async calls are what you really want to keep the JS thread empty, but I did not (and will not, because I have no time) add it. It requires a bit more understanding about the JS/C++ internals, you can't just spawn a thread on C++ and then return data asynchronously to the JS thread, there are some mechanisms to manipulate (AFAIK need to get a hold of the JS context in C++ and some other black magic) in order to implement this. This means: if you really need this, then it's something you will have to implement yourself by looking at libraries like vision-camera or re-animated 2 and submitting a PR.

**Comment by EduFrazao** [comment]
I understand. Thank you @ospfranco . I will see what I can do about it.
I will try to work on it and if it works in my project I will submit a PR.

**Comment by sergeymild** [comment]
> I understand. Thank you @ospfranco . I will see what I can do about it. I will try to work on it and if it works in my project I will submit a PR.

i would be awesome if you make it)
