### ISSUE TITLE
Concurrent use with react-native-sqlite-storage?

### ISSUE THREAD

**Issue by EduFrazao** [ospfranco/react-native-quick-sqlite#5]
Hi. Thank you very mutch this nice project!
Today my project is dependent of react-native-sqlite-storage, and use some features like sqlBatch and transactions.
Its fine for the majority of the workload, but I have some specific scenarios where I need to bulk insert many rows (sometimes more than 500k) and even using transactions or batch inserts, this takes a long time, sometimes more than a minute.
Its mutch more that the classic Cordova SQLite Plugin takes with the same datasource (We have two versions of the same application. The cordova one will be replaced by the react-native version).

I'm wondering if its possible to use this plugin to do such heavy operations, and continue to use react-native-sqlite-storage to continue use transactions, etc. Or its not recommend/possible to open the same database at the same time with two engines.

**Comment by ospfranco** [comment]
I haven't tried it, you should be able to install both but no idea if SQLite will explode

**Comment by EduFrazao** [comment]
> I haven't tried it, you should be able to install both but no idea if SQLite will explode

LOL. Maybe I can open it as a readonly attached database on react-native-sqlite-storage and use your low level API to manipulate this heavy data (its very specific).

But right now, i'm figuring out in how to use it with TypeScript. I can't import the types. There is such examples? I only found examples using TypeORM.

Do you have any plans to add to low level API, features like transactions?
Thank you!

**Comment by ospfranco** [comment]
So, here are some pointers that might help you:

- The stub for attaching to the database: [C++ side](https://github.com/ospfranco/react-native-quick-sqlite/blob/main/cpp/sequel.cpp#L134), the [JSI function definition](https://github.com/ospfranco/react-native-quick-sqlite/blob/main/cpp/react-native-quick-sqlite.cpp#L81) and [registering on the JS side](https://github.com/ospfranco/react-native-quick-sqlite/blob/main/cpp/react-native-quick-sqlite.cpp#L216) you should be able to remove the comment markers and try/test them yourself, but it doesn't look like it would work since the db needs to be opened in order to execute the SQL against it

- When I started the implementation I had a rough batch implementation, however as I went developing the package it became clearer that performance increase was negligible. Batch execution makes a huge difference with packages which go over the old serializable JSON bridge, JSI makes it so fast that it was just a hassle trying to make it work, so I removed it, you might want to give it a try as is and see if performance is acceptable

- Ah, I just took a deeper look into [sqlite-storage](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L125) I thought their transactions were only mutex on database writes but it looks like you only need to execute a `BEGIN` and a `COMMIT` and you should have your transactions... but tbh, I'm busy with other stuff and this looks somewhat easy to implement, so feel free to open a PR

**Comment by ospfranco** [comment]
Just confirmed the types are mangled, there doesn't seem to be a way to declare global variables from a library index.d.ts, I'll try to fix it

**Comment by EduFrazao** [comment]
> Types are fixed in 1.0.3, you still need to do a empty import for typescript to register the types (but the methods should be there with or without types)
> 
> ```
> import 'react-native-quick-sqlite';
> ```

Thank you very mutch @ospfranco . I Will proceed with more tests this week.
Can I do a "off-topic" question? We do heavy use of browser debugger, to inspect code in specific moments, etc.
As it is not possible with this plugin installed on project, do you suggest the use of Flipper. Do you know if its possible to inspect code on it? I did't find any way to do that. Thank you. I will close this bug!

**Comment by ospfranco** [comment]
yep, flipper works just fine! it's even better than the browser debugger console, since it connects to the device (so you don't get different behavior from hermes and the browser JS engine) and there are more and more specific plugins built for it every day... that being said I think there is a way to enable browser debugging for hermes nowadays but I didn't look into it, I just remember seeing a comment about it somewhere

**Comment by themohitkhandal** [comment]
> Hi. Thank you very mutch this nice project! Today my project is dependent of react-native-sqlite-storage, and use some features like sqlBatch and transactions. Its fine for the majority of the workload, but I have some specific scenarios where I need to bulk insert many rows (sometimes more than 500k) and even using transactions or batch inserts, this takes a long time, sometimes more than a minute. Its mutch more that the classic Cordova SQLite Plugin takes with the same datasource (We have two versions of the same application. The cordova one will be replaced by the react-native version).
> 
> I'm wondering if its possible to use this plugin to do such heavy operations, and continue to use react-native-sqlite-storage to continue use transactions, etc. Or its not recommend/possible to open the same database at the same time with two engines.


Hello, can you please provide the syntax of using the  sqlBatch method 
It would be really helpful for me

**Comment by ospfranco** [comment]
This package is deprecated. Use op-sqlite, it has much more performance. See the docs for batch queries usage.
