### ISSUE TITLE
Does it support Web platform?

### ISSUE THREAD

**Issue by b4git** [ospfranco/react-native-quick-sqlite#79]
Does this library support react native web platform as well?

**Comment by ospfranco** [comment]
Nope

**Comment by ospfranco** [comment]
PRs are welcome for anyone that needs web functionality

No idea if browsers dbs support SQL syntax and all the feature set, I assume not.

**Comment by b4git** [comment]
Came across this, but is only for web and not for native: https://sql.js.org/#/
Which says it supports SQLite in browser. We are looking for a use case where performance is critical for live data update and manipulation. So still researching for a lib that supports both react native and web platform.

**Comment by ospfranco** [comment]
You will probably not find such a thing. SQLite is written in C, workarounds might be possible if you compile it to web assembly, but the solution on web is to wrap a higher-level API to insert data to a different database backend (sqlite on native, indexedDb on browsers). Unfortunately, this is not going to work the way you want because this is a low-level library that executes raw SQL queries and does not expose a higher-level API.

**Comment by ospfranco** [comment]
Apparently, people are running that sql.js thing on production:

https://blog.ouseful.info/2022/04/06/compiling-full-text-search-fts5-into-sqlite-wasm-build/

The trade-off is awful though, 6mbs added to the web page load time, I will definitely not implement this on quick-sqlite
